### ISSUE TITLE
[question] About Wind direction calculation

### ISSUE THREAD

**Issue by github0013** [G6EJD/ESP32-Miniature-Weather-Station#2]
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/adc.html

> The ESP32 integrates two 12-bit SAR (Successive Approximation Register) ADCs

12-bit = 4096

https://github.com/G6EJD/ESP32-Miniature-Weather-Station/blob/master/ESP32_Miniature_OLED_Weather_Station_SH1106_v01.ino#L200

> map(winddirection,0,3095,0,359);

I believe esp32's analog pins resolution is 12bit = 4096.   And I see you are using 0 to 3095 for the wind direction analog pin read.

How should I understand why you are using 3096 instead of 4096?

Also, as I understand, wind direction sensor typically uses 8 reed switches + multiple registers like [this one][1].
So that the maximum directions you can tell is 8 * 2 = 16 by this type of sensor.   
I am sure I am missing a lot from [your video][2], but how is your code mapping the analog value to 0-359 (360 degrees of the wind direction, instead of 16 angles)?

[1]: https://projects.raspberrypi.org/en/projects/build-your-own-weather-station/7
[2]: https://www.youtube.com/watch?v=LM0KjpW3hJI

**Comment by G6EJD** [comment]
If you look at the ADC response in 12-bit mode, so will see it is reasonably linear from 0-3v but at the high end it becomes increasingly no -linear so I decided to range the input from 0-2v and then to map that value to 0-359°
Note it is a linear sensor so read switches are no applicable.

you could easily change the 3095 to 4095 and use the full range of the ADC but you will get odd effects and the non-linearity will be apparent.

The mapping function is an inbuilt Arduino function.

Much of the ADC mapping choice depends on the sensor itself.

**Comment by github0013** [comment]
Thank you for your answer.   So I think the wind direction sensor you are using is not what I had in mind.

![Tech_Note_126_-_ESP32_miniature_weather_station_with_wind_direction_add-on_-_YouTube](https://user-images.githubusercontent.com/809378/144935018-8aac63fc-8353-459c-bb87-b538c9386100.png)

One of the links in your description is, I think, not correct? (the link is already gone? and it just redirects to the related category??)
The link page might have been listing the parts (including the linear data type wind direction sensor)?

Anyways thank you for your belief explanation.


Now, if it's just the ADC precision, can you currently adapt [this library][1] to fix it?

[1]: https://www.youtube.com/watch?v=mzlq65fr3uI

**Comment by G6EJD** [comment]
Unfortunately Banggood and other suppliers are always moving their product links. There are 5 different interfaces for the sensors so you have to special attention to the choice made, some choices are serial data, current 2-20mA, 5-20volts and a pulse type. 
yes you can improve ADC linearity with the polynomial approach.
